import { CalculationState, Tools } from "./enums";

export let testState = {
    selectedTool: Tools.AutoDepura,
    calculationState: {
        autodepura: CalculationState.WaitingData,
        colicalc: CalculationState.WaitingData,
    },
    data: {
        autodepura: {
            qr: 0.651,
            odr: 7,
            dbor: 2,
            odmin: 5,
            k120c: 0.38,
            tetak1: 1.047,
            temperatura: 23,
            k1t: null,
            tetak2: 1.024,
            h: null,
            k220c: 3.08,
            k2t: null,
            distancia: 50000,
            velocidade: 0.35,
            particoes: 10,
            tempo: null,
            cs: null,
            cslinha: 7.8,
            qe: 0.114,
            ode: 0,
            dboe: 341,
            dboefl: null,
            e: 0,
            altitude: null,
            lancamentos: null,
        },
        colicalc: {
            qr: 0.651,
            nr: 10,
            volume: 5000000,
            qe: 0.114,
            ne: 50000000,
            nop: 1000,
            temperatura: 23,
            distancia: 50000,
            velocidade: 0.35,
            kb: 1,
            teta: 1.07,
            particoes: 10,
            no: 0,
            ntempo: 0,
            nep: 0,
            kbt: 0,
            eficiencia: 0,
            tempo: 0,
            classLimit: 0,
            represa: false,
            tRepresa: 0,
            tDentencao: 0,
            qAfluente: 0,
            nRepresa: 0,
            nRepresaMax: 0,
        }
    },
    output: {
        autodepura: {
            ctVet: null,
            odminVet: null,
            particoesVet: null,
            kmvet: null,
        },
        colicalc: {
            eficiencia: null,
            particoesVet: null,
            ntempoVet: null,
            kmvet: null,
            novet: null,
        }
    }
}


export let defaultState = {
    selectedTool: Tools.AutoDepura,
    calculationState: {
        autodepura: CalculationState.WaitingData,
        colicalc: CalculationState.WaitingData,
    },
    data: {
        autodepura: {
            qr: null,
            odr: null,
            dbor: null,
            odmin: null,
            k120c: null,
            tetak1: null,
            temperatura: null,
            k1t: null,
            tetak2: null,
            h: null,
            k220c: null,
            k2t: null,
            distancia: null,
            velocidade: null,
            particoes: null,
            tempo: null,
            cs: null,
            cslinha: null,
            qe: null,
            ode: null,
            dboe: null,
            dboefl: null,
            e: null,
            altitude: null,
            lancamentos: null,
        },
        colicalc: {
            qr: null,
            nr: null,
            volume: null,
            qe: null,
            ne: null,
            nop: null,
            temperatura: null,
            distancia: null,
            velocidade: null,
            kb: null,
            teta: null,
            particoes: null,
            no: null,
            ntempo: null,
            nep: null,
            kbt: null,
            eficiencia: null,
            tempo: null,
            classLimit: null,
            represa: null,
            tRepresa: null,
            tDentencao: null,
            qAfluente: null,
            nRepresa: null,
            nRepresaMax: null,
        }
    },
    output: {
        autodepura: {
            ctVet: null,
            odminVet: null,
            particoesVet: null,
            kmvet: null,
        },
        colicalc: {
            eficiencia: null,
            particoesVet: null,
            ntempoVet: null,
            kmvet: null,
            novet: null,
        }
    }
}
