import { CalculationState, Tools } from "./enums";

export let defaultState = {
    selectedTool: Tools.AutoDepura,
    calculationState: {
        autodepura: CalculationState.WaitingData,
        colicalc: CalculationState.WaitingData,
    },
    data: {
        autodepura: {
            qr: null,
            odr: null,
            dbor: null,
            odmin: null,
            k120c: null,
            tetak1: null,
            temperatura: null,
            k1t: null,
            tetak2: null,
            h: null,
            k220c: null,
            k2t: null,
            distancia: null,
            velocidade: null,
            particoes: null,
            tempo: null,
            cs: null,
            cslinha: null,
            qe: null,
            ode: null,
            dboe: null,
            dboefl: null,
            e: null,
            altitude: null,
            lancamentos: null,
        },
        colicalc: {
            qr: null,
            qe: null,
            temperatura: null,
            no: null,
            nop: null,
            nr: null,
            ne: null,
            ntempo: null,
            nep: null,
            kb: null,
            kbt: null,
            teta: null,
            eficiencia: null,
            tempo: null,
            velocidade: null,
            distancia: null,
            particoes: null,
            classLimit: null,
            represa: null,
            tRepresa: null,
            tDentencao: null,
            volume: null,
            qAfluente: null,
            nRepresa: null,
            nRepresaMax: null,
        }
    },
    output: {
        autodepura: {
            ctVet: null,
            odminVet: null,
            particoesVet: null,
            kmvet: null,
        },
        colicalc: {
            eficiencia: null,
            particoesVet: null,
            ntempoVet: null,
            kmvet: null,
            novet: null,
        }
    }
}
